### ISSUE TITLE
Skybox shader need MotionVectors pass?

### ISSUE THREAD

**Issue by zgmtXAX** [oculus-samples/Unity-AppSpaceWarp#4]

**Comment by Daniel-Dobson** [comment]
Which shader are you referring to? Is it one included in this example or one of the Unity ones?

**Comment by meta-benw** [comment]
I'm seeing expected behavior with skyboxes as of https://github.com/oculus-samples/Unity-AppSpaceWarp/commit/b80ca42a777aeaed915810266c7eb88fcf17803f .

Note that skyboxes *don't need* to render motion vectors. Generated motion vectors automatically include motion from head movement since previous frame; since skyboxes are infinitely far away (no parallax) and they don't move, they do not need to do anything extra.
